version: "3.9"

services:

  backend:
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
